server:
  port: 7001

eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称(这里使用了虚拟主机映射，修改hosts文件即可实现)
  client:
#    register-with-eureka: false     #false表示不向注册中心注册自己。
#    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    serviceUrl:
      #单机 defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      defaultZone: http://eureka7002.com:7002/eureka/

spring:
  application:
    name: Eureka-node

