server:
  port: 7002


eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: eureka7002.com
  client:
#    register-with-eureka: false
#    fetch-registry: false
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/
spring:
  application:
    name: Eureka-node
